name: Echo Choice Demo

on:
  workflow_dispatch:
env:
      
 
  work_env: ammar
jobs:
  echo-choice:
    runs-on: ubuntu-22.04
    steps:
      - name: Echo selected environment
        run: |
          echo "You selected: ${{ github.actor }}"
          echo "You selected: ${{ github.repository }}"
      - name: Print environment
        run: echo $GITHUB_SHA