name: Git hub action demo
on: push
jobs:
  action-demo:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the code
        uses: actions/checkout@v4
      - name: print html content
        run: cat index.html
        
 

       
        
  
   
