name: or-demo
on: 
  push:
    branches:
      - main
      - develop
      - feature/**
jobs:
  demo:
    runs-on: ubuntu-latest
    
    steps:

      - name: get actor name
        run: echo "Actor name is ${{ github.actor}} gg"  

      - name: run for mahmoud   or eyad
    
        if: github.actor== 'mahmoud-dayem' || github.actor == 'eyad'
        run: echo "Runnig if mahmoud or eyad"  

 